# rutas.yml
---
ruta_raíz:
    path:     /
    controller: 'funcionHomePage'
    methods:   [ GET ]

ruta_user_list:
    path:     /users
    controller: 'funcionListadoUsuarios'
    methods:
      - GET

ruta_update_user:
    path:     /users/edit/{name}
    controller: 'funcionUpdateUser'
    defaults:
        name: _default_
    methods: [POST]

ruta_create_user:
    path:     /users/newUser
    controller: 'funcionCreateUser'
    methods:
        #- GET
        - POST

ruta_user:
    path:     /users/{name}
    controller: 'funcionUsuario'
    defaults:
        name: _default_
    methods:
        - GET
        - DELETE

ruta_result_list:
    path:     /results
    controller: 'funcionListadoResultados'
    methods:
        - GET

ruta_create_result:
    path: /results/newResult
    controller: 'funcionCreateResult'
    methods:
        #- GET
        - POST

ruta_result:
    path: /results/{id}
    controller: 'funcionResultado'
    defaults:
        id: _default_
    methods:
        - GET
        - DELETE